version: '3'

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.2
    ports:
      - "8086:8086"
      - "2003:2003"
    environment:
      - INFLUXDB_USER=mdd
      - INFLUXDB_USER_PASSWORD=mdd
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - influxdb-data:/var/lib/influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Remplacez par votre propre mot de passe
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  influxdb-data:
  grafana-data:
